arena_account/urls.py
from django.contrib import admin
from django.urls import include, path
from users.api import apis

urlpatterns = [
    # configure user api version-based django views
    path("user/", include(("users.urls", "users"), namespace="v1")),
    path("user/v2/", include(("users.urls", "users"), namespace="v2")),
    # include admin paths
    path("user/admin/", admin.site.urls),
    path("user/accounts/", include("allauth.urls")),
]

# configure user api version-based ninja api endpoints
for version, api in apis.items():
    if version == "v1":
        urlpatterns.insert(0, path("user/", api.urls))  # v1 default
    else:
        urlpatterns.insert(1, path(f"user/{version}/", api.urls))

users/urls.py
from django.urls import path, re_path

from . import views

app_name = "users"
urlpatterns = [
    # views/pages
    path("", views.index, name="index"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path(
        "accounts/3rdparty/signup/",
        views.SocialSignupView.as_view(),
        name="socialaccount_signup",
    ),
    path("profile", views.user_profile, name="user_profile"),
    path("login_callback", views.login_callback, name="login_callback"),
    re_path(r"^profile/namespaces/(?P<pk>[^\/]+)$", views.namespace_perm_detail),
    re_path(r"^profile/scenes/(?P<pk>[^\/]+\/[^\/]+)$", views.scene_perm_detail),
    re_path(r"^profile/devices/(?P<pk>[^\/]+\/[^\/]+)$", views.device_perm_detail),
    # view form submission processing
    path("profile_update_staff", views.profile_update_staff, name="profile_update_staff"),
    path("profile_update_namespace", views.profile_update_namespace, name="profile_update_namespace"),
    path("profile_update_scene", views.profile_update_scene, name="profile_update_scene"),
    path("profile_update_device", views.profile_update_device, name="profile_update_device"),
    # autocomplete
    path(
        "user-autocomplete/",
        views.UserAutocomplete.as_view(),
        name="user-autocomplete",
    ),
    # api docs: served at /doc by Ninja
    # apis: served from users/api.py by Ninja
]

users/forms.py
from allauth.socialaccount.forms import SignupForm as _SocialSignupForm
from dal import autocomplete, forward
from django import forms
from django.conf import settings
from django.contrib.auth.models import User

from .models import Device, Namespace, Scene
from .persistence import read_persist_scenes_by_namespace


class SocialSignupForm(_SocialSignupForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.sociallogin and self.sociallogin.account.provider in ("google"):
            name = self.sociallogin.account.extra_data["email"].split("@")[0]
            self.fields["username"].widget.attrs.update({"value": name})

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get("username")
        # reject usernames in form on signup: settings.USERNAME_RESERVED
        if username in settings.USERNAME_RESERVED:
            msg = f"Sorry, '{username}' is a reserved word."
            self.add_error("username", msg)
        # reject usernames in form on signup: Namespace exists in permissions
        elif Namespace.objects.filter(name=username).exists():
            msg = f"Sorry, '{username}' is a permissions namespace."
            self.add_error("username", msg)
        # reject usernames in form on signup: Namespace used in persist db
        else:
            if len(read_persist_scenes_by_namespace([username])) > 0:
                msg = f"Sorry, '{username}' is a persistence namespace."
                self.add_error("username", msg)

class UpdateStaffForm(forms.Form):
    staff_username = forms.CharField(label="staff_username", required=True)
    is_staff = forms.BooleanField(
        label="is_staff", required=False, initial=False)


class UpdateNamespaceForm(forms.Form):
    add = forms.CharField(label="add", required=False)
    edit = forms.CharField(label="edit", required=False)


class UpdateSceneForm(forms.Form):
    add = forms.CharField(label="add", required=False)
    edit = forms.CharField(label="edit", required=False)


class UpdateDeviceForm(forms.Form):
    add = forms.CharField(label="add", required=False)
    edit = forms.CharField(label="edit", required=False)


class NamespaceForm(forms.ModelForm):
    owners = forms.ModelMultipleChoiceField(
        queryset=User.objects.all().order_by('username'),
        widget=autocomplete.ModelSelect2Multiple(
            url='users:user-autocomplete',
            forward=(forward.Self(), ),
            attrs={'data-minimum-input-length': 2},
        ), required=False)
    editors = forms.ModelMultipleChoiceField(
        queryset=User.objects.all().order_by('username'),
        widget=autocomplete.ModelSelect2Multiple(
            url='users:user-autocomplete',
            forward=(forward.Self(), ),
            attrs={'data-minimum-input-length': 2},
        ), required=False)
    viewers = forms.ModelMultipleChoiceField(
        queryset=User.objects.all().order_by('username'),
        widget=autocomplete.ModelSelect2Multiple(
            url='users:user-autocomplete',
            forward=(forward.Self(), ),
            attrs={'data-minimum-input-length': 2},
        ), required=False)

    class Meta:
        model = Namespace
        fields = ("editors", "viewers")


class SceneForm(forms.ModelForm):
    public_read = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={"class": "form-check-input"}), required=False)
    public_write = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={"class": "form-check-input"}), required=False)
    anonymous_users = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={"class": "form-check-input"}), required=False)
    video_conference = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={"class": "form-check-input"}), required=False)
    users = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={"class": "form-check-input"}), required=False)
    owners = forms.ModelMultipleChoiceField(
        queryset=User.objects.all().order_by('username'),
        widget=autocomplete.ModelSelect2Multiple(
            url='users:user-autocomplete',
            forward=(forward.Self(), ),
            attrs={'data-minimum-input-length': 2},
        ), required=False)
    editors = forms.ModelMultipleChoiceField(
        queryset=User.objects.all().order_by('username'),
        widget=autocomplete.ModelSelect2Multiple(
            url='users:user-autocomplete',
            forward=(forward.Self(), ),
            attrs={'data-minimum-input-length': 2},
        ), required=False)
    viewers = forms.ModelMultipleChoiceField(
        queryset=User.objects.all().order_by('username'),
        widget=autocomplete.ModelSelect2Multiple(
            url='users:user-autocomplete',
            forward=(forward.Self(), ),
            attrs={'data-minimum-input-length': 2},
        ), required=False)

    class Meta:
        model = Scene
        fields = ("public_read", "public_write",
                  "anonymous_users", "video_conference", "users", "editors", "viewers")


class DeviceForm(forms.ModelForm):
    summary = forms.CharField(
        widget=forms.Textarea(attrs={"class": "form-control", "rows": 3}),  required=False)

    class Meta:
        model = Device
        fields = ("summary",)

users/views.py
import datetime
from http import HTTPStatus
from operator import itemgetter

from allauth.socialaccount.views import SignupView as SocialSignupViewDefault
from dal import autocomplete
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import redirect, render

from .filestore import delete_filestore_user, get_filestore_health, set_filestore_scope
from .forms import (
    DeviceForm,
    NamespaceForm,
    SceneForm,
    SocialSignupForm,
    UpdateDeviceForm,
    UpdateNamespaceForm,
    UpdateSceneForm,
    UpdateStaffForm,
)
from .models import Device, Namespace, Scene
from .mqtt import PUBLIC_NAMESPACE, generate_arena_token
from .persistence import (
    delete_persist_namespace_objects,
    delete_persist_scene_objects,
    read_persist_scene_objects,
)
from .utils import (
    get_my_edit_namespaces,
    get_my_edit_scenes,
    namespace_edit_permission,
    scene_edit_permission,
)
from .versioning import API_V1, API_V2, SUPPORTED_API_VERSIONS


def index(request):
    """
    Root page load, index is treated as Login page.
    """
    return redirect("users:login")


def login_request(request):
    """
    Login page load, handles user/pass login if required.
    """
    if request.user.is_authenticated:
        return redirect(f"https://{request.get_host()}/scenes")
    else:
        if request.method == "POST":
            form = AuthenticationForm(request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get("username")
                password = form.cleaned_data.get("password")
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    messages.info(
                        request, f"You are now logged in as {username}.")
                    return redirect("users:login_callback")
                else:
                    messages.error(request, "Invalid username or password.")
            else:
                messages.error(request, "Invalid username or password.")
        form = AuthenticationForm()
        return render(
            request=request, template_name="users/login.html", context={"login_form": form}
        )


def logout_request(request):
    """
    Removes ID and flushes session data, shows login page.
    """
    logout(request)  # revoke django auth
    response = redirect("users:login")
    response.delete_cookie("auth")  # revoke fs auth
    return response


def profile_update_namespace(request):
    """
    Handle User Profile page, namespace post submit requests.
    """
    if request.method != "POST":
        return JsonResponse({}, status=HTTPStatus.BAD_REQUEST)
    if not request.user.is_authenticated:
        return JsonResponse({"error": "Not authenticated."}, status=HTTPStatus.FORBIDDEN)
    form = UpdateNamespaceForm(request.POST)
    if not form.is_valid():
        messages.error(request, "Invalid parameters")
        return redirect("users:user_profile")
    if "add" in request.POST:
        namespacename = request.POST.get("namespacename", None)
        s = Namespace(
            name=f"{namespacename}",
        )
        s.save()
        messages.success(request, f"Created namespace permissions: {namespacename}")
        return redirect("users:user_profile")
    elif "edit" in request.POST:
        name = form.cleaned_data["edit"]
        return redirect(f"profile/namespaces/{name}")

    return redirect("users:user_profile")


def profile_update_scene(request):
    """
    Handle User Profile page, scene post submit requests.
    """
    if request.method != "POST":
        return JsonResponse({}, status=HTTPStatus.BAD_REQUEST)
    if not request.user.is_authenticated:
        return JsonResponse(
            {"error": "Not authenticated."}, status=HTTPStatus.FORBIDDEN
        )
    form = UpdateSceneForm(request.POST)
    if not form.is_valid():
        messages.error(request, "Invalid parameters")
        return redirect("users:user_profile")
    if "add" in request.POST:
        scenename = request.POST.get("scenename", None)
        s = Scene(
            name=f"{request.user.username}/{scenename}",
            summary=f"User {request.user.username} adding new scene {scenename} to account database.",
        )
        s.save()
        messages.success(
            request, f"Created scene permissions: {request.user.username}/{scenename}")
        return redirect("users:user_profile")
    elif "edit" in request.POST:
        name = form.cleaned_data["edit"]
        return redirect(f"profile/scenes/{name}")

    return redirect("users:user_profile")


def profile_update_device(request):
    """
    Handle User Profile page, device post submit requests.
    """
    if request.method != "POST":
        return JsonResponse({}, status=HTTPStatus.BAD_REQUEST)
    if not request.user.is_authenticated:
        return JsonResponse(
            {"error": "Not authenticated."}, status=HTTPStatus.FORBIDDEN
        )
    form = UpdateDeviceForm(request.POST)
    if not form.is_valid():
        messages.error(request, "Invalid parameters")
        return redirect("users:user_profile")
    if "add" in request.POST:
        devicename = request.POST.get("devicename", None)
        s = Device(
            name=f"{request.user.username}/{devicename}",
        )
        s.save()
        messages.success(
            request, f"Created device permissions: {request.user.username}/{devicename}")
        return redirect("users:user_profile")
    elif "edit" in request.POST:
        name = form.cleaned_data["edit"]
        return redirect(f"profile/devices/{name}")

    return redirect("users:user_profile")


def namespace_perm_detail(request, pk):
    """
    Handle Namespace Permissions Edit page, get page load and post submit requests.
    - Handles namespace permissions changes and deletes.
    """
    version = request.version

    if not namespace_edit_permission(user=request.user, namespace=pk):
        messages.error(request, f"User does not have edit permission for namespace: {pk}.")
        return redirect("users:user_profile")
    owners = []
    if User.objects.filter(username=pk).exists():
        owners.append(pk)
    # check if namespace exists before the other commands are tried
    try:
        namespace = Namespace.objects.get(name=pk)
    except Namespace.DoesNotExist:
        namespace = Namespace(name=pk)
    if request.method == "POST":
        if "save" in request.POST:
            form = NamespaceForm(instance=namespace, data=request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, f"Updated namespace permissions: {pk}")
                return redirect("users:user_profile")
        elif "delete" in request.POST:
            # delete account namespace data
            if namespace.pk:
                namespace.delete()
                messages.success(request, f"Removed namespace permissions: {pk}")
            # delete persist objects for this namespace
            if delete_persist_namespace_objects(pk):
                messages.success(request, f"Removed namespace persistence objects: {pk}")

            return redirect("users:user_profile")
    else:
        form = NamespaceForm(instance=namespace)

    return render(
        request=request,
        template_name="users/namespace_perm_detail.html",
        context={"namespace": namespace, "owners": owners, "form": form},
    )


def scene_perm_detail(request, pk):
    """
    Handle Scene Permissions Edit page, get page load and post submit requests.
    - Handles scene permissions changes and deletes.
    """
    version = request.version

    if not scene_edit_permission(user=request.user, scene=pk):
        messages.error(request, f"User does not have edit permission for scene: {pk}.")
        return redirect("users:user_profile")
    owners = [pk.split("/")[0]]
    namespace_editors = []  # TODO: define namespaced_editors
    namespace_viewers = []  # TODO: define namespaced_viewers
    # check if scene exists before the other commands are tried
    try:
        scene = Scene.objects.get(name=pk)
    except Scene.DoesNotExist:
        scene = Scene(name=pk)
    if request.method == "POST":
        if "save" in request.POST:
            form = SceneForm(instance=scene, data=request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, f"Updated scene permissions: {pk}")
                return redirect("users:user_profile")
        elif "delete" in request.POST:
            # delete account scene data
            if scene.pk:
                scene.delete()
                messages.success(request, f"Removed scene permissions: {pk}")
            # delete persist scene data
            namespace, sceneId = pk.split("/")
            if delete_persist_scene_objects(namespace, sceneId):
                messages.success(request, f"Removed scene persisted objects: {pk}")
            else:
                messages.error(request, f"Unable to delete {pk} objects from persistence database.")

            return redirect("users:user_profile")
    else:
        form = SceneForm(instance=scene)

    namespace, sceneId = pk.split("/")
    objects = read_persist_scene_objects(namespace, sceneId)
    objects_updated = None
    if len(objects) > 0:
        updated_ts = sorted(objects, reverse=True, key=itemgetter("updatedAt"))[0]["updatedAt"]
        updated_dt = datetime.datetime.fromisoformat(updated_ts.replace("Z", "+00:00"))
        objects_updated = f"{updated_dt.strftime('%B %d, %Y, %H:%M:%S')} UTC"

    return render(
        request=request,
        template_name="users/scene_perm_detail.html",
        context={
            "scene": scene,

users/templates/users/device_perm_detail.html
{% extends "users/header.html" %}

{% block content %}

{% include 'users/includes/messages.html' %}

<!-- Device Permissions Detail-->
<div class="container-fluid">
    <div class="row d-flex justify-content-center align-items-center min-vh-75">
        <div class="col-md-10 bg-white p-5">

            <h1>Edit Device Permissions</h1>
            {% if token %}
            <small id="tokenHelp" class="form-text text-muted">Keep this MQTT token safe on your device, and do
                not share it with anyone.</small>
            <br>
            <label for="token_username">MQTT Username:</label>
            <div class="input-group mb-3">
                <input id="token_username" name="token_username" class="form-control" readonly
                    value="{{ user.get_username }}"></input>
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" title="Copy to clipboard"
                        onclick="clickCopy('token_username');"><i class="fas fa-copy"></i></button>
                </div>
            </div>
            <label for="token_password">MQTT Password (JWT):</label>
            <div class="input-group mb-3">
                <textarea id="token_password" name="token_password" class="form-control" style="word-break: break-all;"
                    rows="4" readonly>{{ token }}</textarea>
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" title="Copy to clipboard"
                        onclick="clickCopy('token_password');"><i class="fas fa-copy"></i></button>
                </div>
            </div>
            <label for="token_json">Full JSON:</label>
            <div class="input-group mb-3">
                <textarea id="token_json" name="token_json" class="form-control" style="word-break: break-all;" rows="4"
                    readonly>{"username": "{{ user.get_username }}", "token": "{{ token }}"}</textarea>
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" title="Copy to clipboard"
                        onclick="clickCopy('token_json');"><i class="fas fa-copy"></i></button>
                </div>
            </div>
            <hr />
            {% endif %}
            <form id="device_perms_form" action="" method="post">
                {% csrf_token %}
                <table class="table">
                    <tr>
                        <td><b>Device:</b></td>
                        <td><b>{{ device.name }}</b></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td><b>Description:</b></td>
                        <td>{{ form.summary }}</td>
                        <td>Device description.</td>
                    </tr>
                </table>
                <button type="submit" class="btn btn-secondary btn-sm" name="save">Save</button>
                <button type="submit" class="btn btn-secondary btn-sm" name="token">Generate MQTT Token</button>
                <hr />
                <input type="button" class="btn btn-danger btn-sm" onclick="clickDelete(this);"
                    value="Delete Device Permissions" />
            </form>

        </div>
    </div>
    <script>
        function clickCopy(ipput_id) {
            var copyText = document.getElementById(ipput_id);
            copyText.select();
            document.execCommand('copy');
            Swal.fire({
                icon: 'success',
                title: 'Copied!',
                showConfirmButton: false,
                timer: 1000
            })
        }

        async function clickDelete() {
            Swal.fire({
                title: 'Are you sure you want to delete all device permissions for: {{ device.name }}?',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: `Yes`,
                customClass: {
                    cancelButton: 'order-1 right-gap',
                    confirmButton: 'order-2',
                }
            }).then((result) => {
                if (result.isConfirmed) {
                    // submit delete in form manually
                    const form = document.getElementById('device_perms_form');
                    const input = document.createElement('input');
                    input.setAttribute('name', 'delete');
                    form.appendChild(input);
                    form.submit();
                }
            })
        }
    </script>
</div>

{{ form.media }}

{% endblock content %}

users/templates/users/header.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ARENA Users</title>

    {% load static %}

    <link rel="stylesheet" href="{% static 'users/vendor/arenaxr-bootstrap/arenaxr-bootstrap.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'users/vendor/fontawesome/all.min.css'%}" type="text/css">
    <link rel="stylesheet" href="{% static 'users/css/style.css' %}" type="text/css">

    <link rel="shortcut icon" type="image/png" href="{% static 'users/img/conix-x.png' %}" />

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&family=Roboto+Slab&display=swap" rel="stylesheet">

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

    {% block extrahead %}
    {% endblock extrahead %}

</head>

<body>
    {% url 'users:login' as login_url %}
    <!-- avoid navbar for users who have not logged in on login form yet-->
    {% if user.is_authenticated or request.get_full_path != login_url %}

    <style>
        body {
            padding-top: 60px;
        }

        /* fix padding under menu after resize */
        @media screen and (max-width: 767px) {
            body {
                padding-top: 60px;
            }
        }

        @media screen and (min-width:768px) and (max-width: 991px) {
            body {
                padding-top: 110px;
            }
        }

        @media screen and (min-width: 992px) {
            body {
                padding-top: 60px;
            }
        }
    </style>

    <!-- Navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <!-- Container wrapper -->
        <div class="container-fluid">
            <!-- Navbar brand -->
            <a class="navbar-brand" href="/">
                <img alt="arena logo" src="{% static 'users/img/arena-logo-white.png' %}">
            </a>

            <!-- Toggle button -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Collapsible wrapper -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left links -->
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{{request.scheme}}://{{request.get_host}}/scenes">Scenes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{request.scheme}}://{{request.get_host}}/build">Builder</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{request.scheme}}://{{request.get_host}}/programs">Programs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{request.scheme}}://{{request.get_host}}/network">Network</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{request.scheme}}://{{request.get_host}}/files">File Store</a>
                    </li>
                    <li class="nav-item">
                        <!--https://atlas.conix.io-->
                        <a class="nav-link coming-soon" href="/">ATLAS</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://docs.arenaxr.org">Documentation</a>
                    </li>
                </ul>
                <!-- Left links -->

                <!-- Navbar dropdown -->
                <ul class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                    <!-- Dropdown menu -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{user.get_username}}</a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{{request.scheme}}://{{request.get_host}}/conf/versions.html">Version</a></li>
                            <li><a class="dropdown-item" href="{% url 'users:user_profile' %}">Profile</a></li>
                            <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>

            </div>
            <!-- Collapsible wrapper -->
        </div>
        <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->
    <div class="page-header">
        <div class="clearfix">
        </div>
    </div>
    {% endif %}

    {% block content %}

    {% endblock content %}

    <script type="text/javascript" src="{% static 'users/vendor/arenaxr-bootstrap/bootstrap.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script type="text/javascript" src="{% static 'users/vendor/sweetalert2.min.js' %}"></script>

    <script>
        $(document).ready(function() {
            // highlight active page in navbar
            $('.nav-link').filter(function() {
                if (this.href) {
                    const link = new URL(this.href).pathname.replace(/^\/+|\/+$/g, '');
                    const loc = location.pathname.replace(/^\/+|\/+$/g, '');
                    return link == loc;
                }
                return false;
            }).addClass('active');
        });

        $('.coming-soon').on('click', function(e) {
            e.preventDefault();
            alert('COMING SOON');
        });

        function returnToRequestedPage() {
            if (localStorage.getItem("request_uri")) {
                //redirect user to originally requested page
                location.href = localStorage.getItem("request_uri");
                localStorage.removeItem("request_uri");
            } else {
                //redirect user to root page
                location.href = `${window.location.origin}/scenes`;
            }
        }
    </script>

    {% block extrajs %}
    {% endblock extrajs %}
</body>

</html>

users/templates/users/login_callback.html
{% extends "users/header.html" %}

{% block content %}

<!--Login Callback-->
<div class="container p-5">
    {% include 'users/includes/messages.html' %}
    <p>
        Redirecting to requested resource...
    </p>
</div>
<script>
    window.onload = function() {
        localStorage.setItem("auth_choice", "google");
        returnToRequestedPage();
    };
</script>
{% endblock content %}

users/templates/users/social_signup.html
{% extends "users/header.html" %}
{% load static %}
{% load account %}
{% load socialaccount %}

{% block content %}

{% include 'users/includes/messages.html' %}

<!--Social Sign Up-->
<div class="container-fluid">
    <div class="row d-flex justify-content-center align-items-center">
        <div class="col-lg-7 col-md-8 shadow rounded bg-white p-5">

            <h3>Sign Up</h3>
            <p>You are about to use your
                {{account.get_provider.name}} account to login to ARENA. As a final step, please complete the
                following form:</p>
            <form class="signup" id="signup_form" method="post" action="{% url 'users:socialaccount_signup' %}"
                enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                <p>
                    {{ field.label_tag }}<br>
                    {{ field }}
                    {% if field.help_text %}
                    <small style="color: grey">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                <p style="color: red">{{ error }}</p>
                {% endfor %}
                </p>
                {% endfor %}
                {% if redirect_field_value %}
                <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                {% endif %}
                <button type="submit" class="btn btn-secondary">Sign Up &raquo;</button>
            </form>
        </div>
    </div>
</div>

{% endblock content %}